### ISSUE TITLE
Mapper Rules: Fake entities 

### ISSUE THREAD

**Issue by 12pm** [12pm/ddnet-mapping#1]
Add a rule regarding fake entities?
Something like: "Do not use fake entities for gameplay" - "Make sure that there are no fake entities" as well as an explanation of what a fake entity is.

**Comment by gamertyp** [comment]
Is this a thing you can find in current maps?

**Comment by 12pm** [comment]
It's used for trolling purpuses sometimes, maybe it's obvious that you shouldn't use it for gameplay tho.

**Comment by gamertyp** [comment]
Imo there shouldn't be more rules than really needed. If this isn't an actual problem, I wouldn't add it.
