### ISSUE TITLE
Excessively tight parts

### ISSUE THREAD

**Issue by gamertyp** [12pm/ddnet-mapping#2]
"excessively tight parts."

This sounds too extreme imo, thus to limited.

**Comment by Piepow** [comment]
I don't know what level of emphasis you prefer, so you should probably re-word it yourself :)

**Comment by gamertyp** [comment]
It's rather about unnecessarily tight parts. A tight gores in an Insane map is totally fine, but an tight drag part with bigger groups is really annoying.

**Comment by 12pm** [comment]
I guess this is fine https://github.com/12pm/ddnet-mapping/commit/f8c9116d916aa146c8c935022bc7817e3c909701
