### ISSUE TITLE
General style

### ISSUE THREAD

**Issue by gamertyp** [12pm/ddnet-mapping#4]
Imo the rules should be rather written as an "is-state", instead of how it "should" be.

**Comment by 12pm** [comment]
Hm people should start following the rules as soon as they start mapping a map, not after it's finished.
I think that's more clear and generaly easier to understand if it's written in the "should" style.

**Comment by Piepow** [comment]
Since the pretense is "check out these tips," each tip should be written in an affirmative style (do this, do that, make sure that _xxx_ is done, ensure that _xxx_ is whatever, etc.)

**Comment by 12pm** [comment]
Let's keep the should style.
