### ISSUE TITLE
Team Size Rule

### ISSUE THREAD

**Issue by gamertyp** [12pm/ddnet-mapping#5]
A map should only require a restricted team size, if it really makes sense.
2 player for dummy maps, parts which won't work in groups and so on.

If it is only used, because the mapper wasn't able to map properly, the map should be reworked.

**Comment by 12pm** [comment]
Make sense to add this. 
I think dummy maps don't need extra team size settings tho, since it's enforced by the server anyways (should ask an Admin to make sure).

**Comment by 12pm** [comment]
https://github.com/12pm/ddnet-mapping/commit/d09e0ec22f5c3bc917109c1d70a0107db590c8c9
